import os
import google.generativeai as genai
from dotenv import load_dotenv
load_dotenv()

class GeminiDocumentGenerator:
    def __init__(self):
        api_key = os.getenv("GEMINI_API_KEY")
        if not api_key or "YOUR_API" in api_key:
            self.model = None
            return
        genai.configure(api_key=api_key)
        self.model = genai.GenerativeModel("gemini-1.5-pro")

    def generate_document(self, document_type, parties, terms, effective_date):
        prompt = f"""You are senior legal counsel. Draft professional {document_type}.
        Parties: {parties}
        Date: {effective_date}
        Terms: {terms}
        Include: Title, Recitals, Definitions, Clauses, Payment, Confidentiality, Termination, Governing Law, Signatures."""

        if self.model is None:
            return self._fallback(document_type, parties, terms, effective_date)
        try:
            res = self.model.generate_content(prompt)
            return res.text
        except:
            return self._fallback(document_type, parties, terms, effective_date)

    def _fallback(self, doc_type, parties, terms, date):
        t_list = [t.strip() for t in terms.split(';') if t.strip()]
        bullets = "\n".join([f"{i}. {t}" for i,t in enumerate(t_list,1)])
        return f"""{doc_type.upper()}
Date: {date}
Between: {parties}

1. BACKGROUND
This {doc_type} is made between {parties} effective {date}.

2. TERMS & CONDITIONS
{bullets}

3. CONFIDENTIALITY
Both parties maintain confidentiality for 2 years.

4. TERMINATION
Either party may terminate with 15 days notice.

5. GOVERNING LAW
Governed by laws of India.

SIGNATURES:
__________________ __________________
{parties}

Generated by LegalEase
"""
